# Generated by Django 4.0.4 on 2022-04-17 18:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_store', '0003_alter_customer_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
