# Generated by Django 4.0.4 on 2022-04-19 17:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('food_store', '0005_alter_fooditem_description'),
    ]

    # operations = [
    #     migrations.AlterField(
    #         model_name='cart',
    #         name='id',
    #         field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
    #     ),
    # ]
    operations = [
        migrations.RemoveField('cart', 'id'),
        migrations.AddField(
            model_name='cart',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        )
    ]
