# Generated by Django 4.0.4 on 2022-04-20 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_store', '0006_alter_cart_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'fooditem')},
        ),
    ]
