# Generated by Django 4.0.5 on 2022-06-10 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_store', '0011_customer_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='last_name',
        ),
    ]
